### Creaate blog post
POST https://api.linkedin.com/rest/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer xxx
LinkedIn-Version: 202308
X-Restli-Protocol-Version: 2.0.0

{
  "author": "urn:li:organization:5515715",
  "commentary": "Sample video Post",
  "visibility": "PUBLIC",
  "distribution": {
    "feedDistribution": "MAIN_FEED",
    "targetEntities": [],
    "thirdPartyDistributionChannels": []
  },
  "content": {
    "media": {
      "title":"title of the video",
      "id": "urn:li:video:C5F10AQGKQg_6y2a4sQ"
    }
  },
  "lifecycleState": "PUBLISHED",
  "isReshareDisabledByAuthor": false
}


### Update post
POST https://api.linkedin.com/rest/posts/{shareUrn}/{ugcPostUrn}
Content-Type: application/json
Authorization: Bearer xxx
LinkedIn-Version: 202308
X-Restli-Protocol-Version: 2.0.0
X-RestLi-Method: PARTIAL_UPDATE

{
    "patch":
    {
        "$set":
        {
            "commentary": "Update to the post",
            "contentCallToActionLabel": "LEARN_MORE"
        },
        "adContext":
        {
            "$set":
            {
                "dscName": "Updating name!"
            }
        }
    }
}

### Delete post
DELETE https://api.linkedin.com/rest/posts/{encoded ugcPostUrn|shareUrn}
Content-Type: application/json
Authorization: Bearer xxx
LinkedIn-Version: 202308
X-Restli-Protocol-Version: 2.0.0
X-RestLi-Method: DELETE
