version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "web"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]

  - package-ecosystem: "npm"
    directory: "/hub"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "hub"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
  
  - package-ecosystem: "npm"
    directory: "/back"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "back"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
