services:
  app:
    image: carloswufei/jobhub
    restart: always
    container_name: jobhub_app
    depends_on:
      - web
    env_file:
      - .env
    ports:
      - "8081:8081"
      - "8080:8080"
    command:
      - bash
      - -c
      - /home/wait-for-it.sh web:3000 -- nginx -t && exec nginx -g 'daemon off;'

  web:
    image: carloswufei/jobhub
    restart: always
    container_name: jobhub_web
    env_file:
      - .env
    expose:
      - "3000"
    command:
      - bash
      - -c
      - cd /home/web && npm run start

  back:
    image: carloswufei/jobhub
    restart: always
    container_name: jobhub_back
    depends_on:
      - db
    env_file:
      - .env
    environment:
      MEDIUM_API_TOKEN: 2a3833154fa181728499e0c2ddc0ec6f92b0be3cc07f9e22eb6aa14e7c4347033
      MONGO_CONNECTION_STRING: mongodb://db/cv_generator
      GOOGLE_APPLICATION_CREDENTIALS: /home/back/jobhub-415000-prod.json
      HOST: db
      BACK_PORT: 8082
    ports:
      - "8082:8082"
    command:
      - bash
      - -c
      - /home/wait-for-it.sh db:27017 -- node /home/back/dist/server.js
    volumes:
      - ./jobhub-415000-prod.json:/home/back/jobhub-415000-prod.json
      - ./back/docs:/home/back/docs
      - ./back/uploads:/home/back/uploads

  db:
    image: mongo:7.0
    container_name: jobhub_db
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_AUTH_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_AUTH_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_db:/data/db

volumes:
  mongo_db:
