POST http://localhost:8082/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "categories": "test",
    "content": "<p>HTML content</p>"
}

###
GET http://localhost:8082/api/blogs HTTP/1.1

###
GET http://localhost:8082/api/blogs/5fe7e810793b6930b71cb6c0 HTTP/1.1

###
DELETE http://localhost:8082/api/blogs/5fe7e810793b6930b71cb6c0 HTTP/1.1


### Categories and tags
POST http://localhost:8082/api/cats HTTP/1.1
content-type: application/json

{
    "title": "Categories",
    "label": "categories",
    "singLabel": "category",
    "children": [
        {
            "value": "dev",
            "text": "Programming",
            "rank": 0
        },
        {
            "value": "travel",
            "text": "Travel",
            "rank": 0
        },
        {
            "value": "biz",
            "text": "Business",
            "rank": 0
        }
    ]
}

### Tags
POST http://localhost:8082/api/cats/tags HTTP/1.1
content-type: application/json

{
    "title": "Tags",
    "label": "tags",
    "singLabel": "tag",
    "children": [
        {
            "value": "web",
            "text": "web",
            "rank": 0
        }
    ]
}

###
GET http://localhost:8082/api/cats HTTP/1.1

###
DELETE http://localhost:8082/api/cats/5fe7c35da0004018e7c6d8d0 HTTP/1.1

### Search by title of blog (Name)
GET http://localhost:8082/api/blogs/name/Test%20markdown HTTP/1.1

### Search by topic (Filter)
GET http://localhost:8082/api/blogs/category/dev HTTP/1.1
