name: Deployment CI

on: "pull_request"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      run: docker build --tag jobhub . 
    - name: Test docker container
      run: |
        docker run --detach --publish 80:80 jobhub
        sleep 3
        curl --retry-delay 1 --retry 30 --retry-connrefused http://localhost
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: carloswufei/jobhub
        tags: latest
