name: PR checks
on: pull_request
env:
  ACTIONS_RUNNER_DEBUG: true
  SECRET_KEY: test
  MONGO_DATABASE: cv_generator
  MONGO_AUTH_USERNAME: test
  MONGO_AUTH_PASSWORD: root_password
  MONGO_HOSTNAME: jobhub_db
  BACK_PORT: 8082
  JWT_SECRET: root_password
  HUB_URL: http://localhost:8081
  WEB_URL: http://localhost:8080


jobs:
  push_to_registry:
    name: Test and deploy jobhub web apps
    runs-on: ubuntu-latest
    services:
      jobhub_db:
        image: mongo:latest
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh jobhub_db:27017/cv_generator --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_AUTH_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_AUTH_PASSWORD }}
        ports:
          - 27017:27017


    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build --tag jobhub .
      - name: Test server rendering
        run: |
          docker run --publish 8083:8083 --name jobhub_app -d jobhub
          sleep 10
          docker logs jobhub_app
          curl --head --fail --retry-delay 5 --retry 3 --retry-connrefused http://localhost:8083
      - name: Test hub
        run: |
          docker exec jobhub_app sh -c "service nginx start"
          curl --head --fail --retry-delay 5 --retry 3 --retry-connrefused http://localhost:8081
      - name: Test web
        run: curl --head --fail --retry-delay 5 --retry 3 --retry-connrefused http://localhost
      - name: Tag image
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          docker commit jobhub &
          docker tag jobhub carloswufei/jobhub
      - name: Push to Docker Hub
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: carloswufei/jobhub
          tags: "latest"

  back:
    name: Test and deploy jobhub API
    runs-on: ubuntu-latest
    services:
      jobhub_db:
        image: mongo:latest
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh jobhub_db:27017/cv_generator --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_AUTH_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_AUTH_PASSWORD }}
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@master
      - name: Build docker image for jobhub_back
        run: docker build --tag jobhub_back ./back
      - name: Run image
        run: |
          docker run --network host --name jobhub_back \
            -e MONGO_AUTH_USERNAME=${{ env.MONGO_AUTH_USERNAME }} \
            -e MONGO_AUTH_PASSWORD=${{ env.MONGO_AUTH_PASSWORD }} \
            -e MONGO_DATABASE=${{ env.MONGO_DATABASE }} \
            -e BACK_PORT=${{ env.BACK_PORT }} \
            -e HUB_URL=${{ env.HUB_URL }} \
            -e WEB_URL=${{ env.WEB_URL }} \
            -e GITHUB_ACTIONS=true -d jobhub_back
          sleep 3
          docker ps
          curl --head --fail --retry-delay 2 --retry 10 --retry-connrefused http://localhost:${{ env.BACK_PORT }}/api
      - name: Tag image
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          docker commit jobhub_back carloswufei/jobhub_back &
          docker tag jobhub_back carloswufei/jobhub_back
      - name: Push to Docker Hub
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push carloswufei/jobhub_back
