name: PR checks
on: pull_request
env:
  ACTIONS_RUNNER_DEBUG: true
  SECRET_KEY: test
  MONGO_DATABASE: cv_generator
  MONGO_AUTH_USERNAME: test
  MONGO_AUTH_PASSWORD: root_password
  MONGO_HOSTNAME: jobhub_db
  BACK_PORT: 8082
  JWT_SECRET: root_password
  HUB_URL: http://localhost:8081
  WEB_URL: http://localhost:8080


jobs:
  push_to_registry:
    name: Test and deploy jobhub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build --tag jobhub .
      - name: Test back
        run: |
          docker run --network host --name jobhub_app \
          -e GITHUB_ACTIONS=true -d jobhub
          docker ps
      - name: Test hub
        run: |
          docker exec jobhub_app sh -c "service nginx start"
          curl --head --fail --retry-delay 5 --retry 3 --retry-connrefused http://localhost:8081
      - name: Test web
        run: |
          curl --head --fail --retry-delay 5 --retry 3 --retry-connrefused http://localhost
      - name: Tag image
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          docker commit jobhub &
          docker tag jobhub carloswufei/jobhub
      - name: Push to Docker Hub
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: carloswufei/jobhub
          tags: "latest"
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
