name: PR checks
on: pull_request
env:
  ACTIONS_RUNNER_DEBUG: true
  SECRET_KEY: test
  ENV: ci
  MONGO_HOSTNAME: localhost
  MONGO_PORT: 27018
  MONGO_AUTH_DATABASE: cv_generator
  MONGO_AUTH_USERNAME: carkod
  MONGO_AUTH_PASSWORD: 48295620-j
  BACK_PORT: 8082
  MONGO_CONNECTION_STRING: "mongodb://localhost:27017/cv_generator"
  JWT_SECRET: 48295620-j
  HUB_URL: http://localhost:8081
  WEB_URL: http://localhost:8080


jobs:
  push_to_registry:
    name: Test and deploy jobhub
    runs-on: ubuntu-latest
    services:
      jobhub_db:
        image: mongo:latest
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_AUTH_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_AUTH_PASSWORD }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build --tag jobhub .
      - name: Test hub
        run: |
          docker run -d --network host jobhub
          sleep 5
          curl --head --fail --retry-delay 5 --retry 3 --retry-connrefused http://localhost:8081
      - name: Test web
        run: |
          curl --head --fail --retry-delay 5 --retry 3 --retry-connrefused http://localhost:8080
      - name: Tag image
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          docker commit jobhub &
          docker tag jobhub carloswufei/jobhub
      - name: Push to Docker Hub
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: carloswufei/jobhub
          tags: "latest"
